default: &default
  # adapter: sqlite3 変更
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8 #変更
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost # 追加

development:
  <<: *default
  # database: db/development.sqlite3 変更
  database: testDB

test:
  <<: *default
  # database: db/test.sqlite3 変更
  database: testDB

# Herokuデプロイ時に再度見直す
production:
  <<: *default
  # database: db/production.sqlite3 変更
  password: <%= ENV['DATABASE_PASSWORD'] %>